// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-configured account alias metadata for an app.
 */
export type AppAccountAliasInfo = { key: string, name: string, description: string | null, isDefault: boolean, };
