// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppAccountAliasInfo } from "./AppAccountAliasInfo";

/**
 * User-configured account selection metadata for an app.
 */
export type AppAccountSelectionInfo = { aliases: Array<AppAccountAliasInfo>, askWhenUnspecified: boolean, };
