// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppAccountSelectionInfo } from "./AppAccountSelectionInfo";
import type { AppInfo } from "./AppInfo";

/**
 * EXPERIMENTAL - app list response.
 */
export type AppsListResponse = { data: Array<AppInfo>, accountSelection: { [key in string]?: AppAccountSelectionInfo },
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * If None, there are no more items to return.
 */
nextCursor: string | null, };
